version: '3.9'

networks:
  instantbet-account:
    driver: bridge

services:
  postgres:
    hostname: instantbet-account
    container_name: instanbet-acc-postgres
    image: postgres:15.5
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - instantbet-account
    healthcheck:
      test: 'exit 0'

  pgadmin:
    container_name: instanbet-acc-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_USERNAME}@${APP_OWNER}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    networks:
      - instantbet-account
    depends_on:
      - postgres

  acc-app:
    container_name: instanbet-acc
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - ENV=${ENV}
    env_file:
      - ${ENV_FILE}
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - instantbet-account
    volumes:
      - acc-app:/usr/src/logs
      # - ./home/data_spartan/stefanProj/.keys/instantbet:/usr/.keys/instantbet
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin

volumes:
  acc-app:
    driver: local
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
