version: '3.9'

services:
  postgres:
    container_name: '${APP_NAME}-Postgres'
    image: postgres:15.5
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - 'postgres_data:/var/lib/postgresql'
    healthcheck:
      test: 'exit 0'

  pgadmin:
    container_name: '${APP_NAME}-PGAdmin'
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DATABASE_USERNAME}@${APP_OWNER}
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - 'pgadmin_data:/var/lib/pgadmin'
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
