version: '3.9'

networks:
  instantbet-account:
    driver: bridge

services:
  postgres:
    hostname: instantbet-account
    image: postgres:15.5
    container_name: instanbet-acc-postgres
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - instantbet-account
    healthcheck:
      test: exit 0

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: instanbet-acc-pgadmin
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_USERNAME}@${APP_OWNER}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - instantbet-account
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: instanbet-acc-redis
    hostname: ${REDIS_HOSTNAME}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
    # inter port must be always 6379 bcs thats default port of docker redis unless you bind redis.conf file to docker volume
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    networks:
      - instantbet-account
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: instantbet-acc-redis-commander
    depends_on:
      - redis
    ports:
      - ${COMMANDER_PORT}:8081
    environment:
      - REDIS_HOST=${REDIS_HOSTNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - instantbet-account
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: instantbet-acc-rabbitmq
    hostname: rabbitmq
    volumes:
      - rabitmq-data:/var/lib/rabbitmq
      - rabitmq-logs:/var/log/rabbitmq
      # - ~/.rabit-conf/:/etc/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - instantbet-account
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}
    restart: unless-stopped

  acc-app:
    container_name: instanbet-acc-app
    build:
      context: ./
      dockerfile: ./apps/account/Dockerfile
      # args:
      #   - ENV=${ENV}
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - instantbet-account
    volumes:
      - acc-app:/usr/src/logs
      - ./uploads:/usr/src/uploads
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin
      - redis

  notifications-app:
    container_name: instanbet-notifications
    build:
      context: ./
      dockerfile: ./apps/notifications/Dockerfile
      # args:
      #   - ENV=${ENV}
    env_file:
      - .env
    ports:
      - ${NOTIFICATIONS_PORT}:${NOTIFICATIONS_PORT}
    networks:
      - instantbet-account
    volumes:
      - notifications-app:/usr/src/logs
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - acc-app
      

volumes:
  acc-app:
    driver: local
  notifications-app:
    driver: local
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  redis-data:
    driver: local
  rabitmq-data:
    driver: local
  rabitmq-logs:
    driver: local
