export enum MailerConfigEnum {
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_USERNAME = 'EMAIL_USERNAME',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
  NO_REPLY_EMAIL = 'NO_REPLY_EMAIL',
}
