export enum ServeStaticConfigEnum {
  APP_FILE_PUBLIC_IMAGES_DIR = 'APP_FILE_PUBLIC_IMAGES_DIR',
  APP_FILE_SERVE_PUBLIC_URL = 'APP_FILE_SERVE_PUBLIC_URL',
  APP_FILE_TEMP_IMAGES_DIR = 'APP_FILE_TEMP_IMAGES_DIR',
  APP_API_PREFIX = 'APP_API_PREFIX',
}
